import type { WardrobeItem, WardrobeSlot } from './types';

const CUSTOM_SOURCE = {
  name: 'Winston 2.0 procedural accessory',
  url: 'https://github.com/pgil256/winston-2',
  license: 'Custom',
} as const;

const KHRONOS_SAMPLE_SOURCES = {
  boxVertexColors: {
    name: 'Khronos glTF Sample Assets - Box Vertex Colors',
    url: 'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BoxVertexColors',
    license: 'CC0',
    attribution: 'Marco Hutter for Everything',
  },
  compareClearcoat: {
    name: 'Khronos glTF Sample Assets - Compare Clearcoat',
    url: 'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CompareClearcoat',
    license: 'CC0',
    attribution: 'Eric Chadwick and DGG for Everything',
  },
  clearcoatWicker: {
    name: 'Khronos glTF Sample Assets - Clearcoat Wicker',
    url: 'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ClearcoatWicker',
    license: 'CC0',
    attribution: 'Eric Chadwick for Everything',
  },
  interpolationTest: {
    name: 'Khronos glTF Sample Assets - Interpolation Test',
    url: 'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/InterpolationTest',
    license: 'CC0',
    attribution: 'Khronos for Everything',
  },
} as const;

export const allWardrobeItems: readonly WardrobeItem[] = [
  {
    id: 'top-hat',
    label: 'Top Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'TopHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.029, -0.01], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['classic', 'fancy'],
  },
  {
    id: 'party-hat',
    label: 'Party Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'PartyHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.029, -0.01], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['party', 'playful'],
  },
  {
    id: 'witch-hat',
    label: 'Witch Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'WitchHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.029, -0.01], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['magic', 'costume'],
  },
  {
    id: 'cowboy-hat',
    label: 'Cowboy Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'CowboyHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.029, -0.01], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['western', 'costume'],
  },
  {
    id: 'crown',
    label: 'Crown',
    slot: 'head',
    kind: 'procedural',
    component: 'Crown',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.025, -0.005], rotation: [0, 0, 0], scale: 0.5 },
    tags: ['royal', 'playful'],
  },
  {
    id: 'wizard-hat',
    label: 'Wizard Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'WizardHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.03, -0.005], rotation: [0, 0, 0], scale: 0.5 },
    tags: ['magic', 'fantasy'],
  },
  {
    id: 'pirate-hat',
    label: 'Pirate Hat',
    slot: 'head',
    kind: 'procedural',
    component: 'PirateHat',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'headCrown', position: [0, -0.026, -0.005], rotation: [0, 0, 0], scale: 0.5 },
    tags: ['pirate', 'adventure'],
  },
  {
    id: 'sample-motion-cube',
    label: 'Motion Cube',
    slot: 'head',
    kind: 'glb',
    assetPath: '/models/accessories/sample-motion-cube.glb',
    source: KHRONOS_SAMPLE_SOURCES.interpolationTest,
    transform: { anchor: 'headCrown', position: [0, -0.035, -0.005], rotation: [0, 0, 0], scale: 0.012 },
    tags: ['playful', 'glb'],
  },
  {
    id: 'sunglasses',
    label: 'Sunglasses',
    slot: 'face',
    kind: 'procedural',
    component: 'Sunglasses',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'faceBridge', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.72 },
    tags: ['cool', 'playful'],
  },
  {
    id: 'eyepatch',
    label: 'Eyepatch',
    slot: 'face',
    kind: 'procedural',
    component: 'Eyepatch',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'faceBridge', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.72 },
    tags: ['pirate', 'adventure'],
  },
  {
    id: 'bowtie',
    label: 'Bowtie',
    slot: 'neck',
    kind: 'procedural',
    component: 'Bowtie',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'chestFront', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['formal', 'pet-fashion'],
  },
  {
    id: 'collar',
    label: 'Collar',
    slot: 'neck',
    kind: 'procedural',
    component: 'Collar',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'chestFront', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['pet-fashion', 'bell'],
  },
  {
    id: 'scarf',
    label: 'Scarf',
    slot: 'neck',
    kind: 'procedural',
    component: 'Scarf',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'chestFront', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['cozy', 'pet-fashion'],
  },
  {
    id: 'sample-wicker-orb',
    label: 'Wicker Charm',
    slot: 'neck',
    kind: 'glb',
    assetPath: '/models/accessories/sample-wicker-orb.glb',
    source: KHRONOS_SAMPLE_SOURCES.clearcoatWicker,
    transform: { anchor: 'chestFront', position: [0, -0.035, 0.01], rotation: [0, 0, 0], scale: 0.055 },
    tags: ['charm', 'glb'],
  },
  {
    id: 'sweater',
    label: 'Sweater',
    slot: 'body',
    kind: 'procedural',
    component: 'Sweater',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'waist', position: [0, 0.02, 0.06], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['cozy', 'pet-fashion'],
  },
  {
    id: 'tutu',
    label: 'Tutu',
    slot: 'body',
    kind: 'procedural',
    component: 'Tutu',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'waist', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['dance', 'playful'],
  },
  {
    id: 'sample-toy-block',
    label: 'Toy Block',
    slot: 'body',
    kind: 'glb',
    assetPath: '/models/accessories/sample-toy-block.glb',
    source: KHRONOS_SAMPLE_SOURCES.boxVertexColors,
    transform: { anchor: 'waist', position: [-0.035, -0.02, 0.05], rotation: [0, 0, 0], scale: 0.06 },
    tags: ['toy', 'glb'],
  },
  {
    id: 'cape',
    label: 'Cape',
    slot: 'back',
    kind: 'procedural',
    component: 'Cape',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'upperBack', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.42 },
    tags: ['hero', 'costume'],
  },
  {
    id: 'wings',
    label: 'Wings',
    slot: 'back',
    kind: 'procedural',
    component: 'Wings',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'upperBack', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.8 },
    tags: ['fantasy', 'playful'],
  },
  {
    id: 'backpack',
    label: 'Backpack',
    slot: 'back',
    kind: 'procedural',
    component: 'Backpack',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'upperBack', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.75 },
    tags: ['adventure', 'space'],
  },
  {
    id: 'sample-clearcoat-tiles',
    label: 'Clearcoat Tiles',
    slot: 'back',
    kind: 'glb',
    assetPath: '/models/accessories/sample-clearcoat-tiles.glb',
    source: KHRONOS_SAMPLE_SOURCES.compareClearcoat,
    transform: { anchor: 'upperBack', position: [0, -0.01, -0.025], rotation: [0, 0, 0], scale: 0.045 },
    tags: ['shiny', 'glb'],
  },
  {
    id: 'socks',
    label: 'Socks',
    slot: 'feet',
    kind: 'procedural',
    component: 'Socks',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'frontPawL', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['cozy', 'pet-fashion'],
  },
  {
    id: 'boots',
    label: 'Boots',
    slot: 'feet',
    kind: 'procedural',
    component: 'Boots',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'frontPawL', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['adventure', 'pet-fashion'],
  },
  {
    id: 'slippers',
    label: 'Slippers',
    slot: 'feet',
    kind: 'procedural',
    component: 'Slippers',
    source: CUSTOM_SOURCE,
    transform: { anchor: 'frontPawL', position: [0, 0, 0], rotation: [0, 0, 0], scale: 0.55 },
    tags: ['cozy', 'pet-fashion'],
  },
];

const ITEMS_BY_ID = new Map(allWardrobeItems.map((item) => [item.id, item]));

export function getWardrobeItem(id: string): WardrobeItem | undefined {
  return ITEMS_BY_ID.get(id);
}

export function itemsForSlot(slot: WardrobeSlot): readonly WardrobeItem[] {
  return allWardrobeItems.filter((item) => item.slot === slot);
}
